networks:
  darknet:
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

services:
  tor:
    build: ./tor
    image: tor:mk
    container_name: tor
    environment:
      - TZ=${TZ}
    expose:
      - 9050
    networks:
      darknet:
        ipv4_address: 172.20.0.2

  pyload:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    depends_on:
      - tor
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      darknet:
        ipv4_address: 172.20.0.3
    volumes:
      - ./config:/config
      - ${DATA_PATH}/torload/downloads:/downloads
    ports:
      - 8000:8000
    restart: unless-stopped
