# https://doc.traefik.io/traefik/
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.11
    container_name: traefik
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    command:
      #- "--log.level=DEBUG"
      #- "--accesslog=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--certificatesresolvers.dns_certresolver.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.dns_certresolver.acme.email=omv_contact@kllnr.de"
      - "--certificatesresolvers.dns_certresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ${DATA_PATH}/traefik/letsencrypt:/letsencrypt
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: proxy
