---
services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    group_add:
      - "${DOCKER_GID}"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

    ports:
      - "80:8080"
      - "443:8443"

    volumes:
      - "${DATA_PATH}/traefik/letsencrypt:/letsencrypt"
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

    command:
      # EntryPoints
      - "--entrypoints.web.address=:8080"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:8443"
      - "--entrypoints.websecure.http.tls=true"

      # Providers 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # - "--providers.docker.network=proxy"

      # API & Dashboard 
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # Observability 
      - "--log.level=INFO"
      - "--accesslog=true"
      # - "--metrics.prometheus=true"

      # ... other command arguments ...
      - "--certificatesresolvers.dns_certresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.dns_certresolver.acme.storage=/letsencrypt/acme.json" # Path inside container volume
      - "--certificatesresolvers.dns_certresolver.acme.httpchallenge.entrypoint=web"

      # - "--certificatesresolvers.dns_certresolver.acme.dnschallenge.provider=your-dns-provider" # Needs provider setup

      # Optionally make 'dns_certresolver' the default resolver for TLS-enabled routers
      - "--entrypoints.websecure.http.tls.certresolver=dns_certresolver"
