---
services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    group_add:
      - "${DOCKER_GID}"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"

    volumes:
      - "${AMCME_CERTS_DIR:-./letsencrypt}:/letsencrypt"
      # So that Traefik can listen to the Docker events
      - "${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock:ro"

    command:
      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      # Providers 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"

      # API & Dashboard 
      - "--api.dashboard=${DASHBOARD:-false}"
      - "--api.insecure=${INSECURE:-false}"

      # Observability 
      - "--log.level=${LOG_LEVEL:-ERROR}"
      - "--accesslog=${ACCESS_LOG:-true}"
      # - "--metrics.prometheus=true"

      # ... other command arguments ...
      - "--certificatesresolvers.dns_certresolver.acme.email=${ACME_MAIL:-example@example.org}"
      - "--certificatesresolvers.dns_certresolver.acme.storage=/letsencrypt/acme.json" # Path inside container volume
      - "--certificatesresolvers.dns_certresolver.acme.httpchallenge.entrypoint=web"

      # - "--certificatesresolvers.dns_certresolver.acme.dnschallenge.provider=your-dns-provider" # Needs provider setup

      # Optionally make 'dns_certresolver' the default resolver for TLS-enabled routers
      - "--entrypoints.websecure.http.tls.certresolver=dns_certresolver"
      # Traefik Dynamic configuration via Docker labels
    labels:
      # Enable self‑routing
      - "traefik.enable=true"

      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`${DOMAIN:-traefik.test}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      # Basic‑auth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${BASIC_AUTH_USERS:-admin:$$apr1$$4vqie50r$$YQAmQdtmz5n9rEALhxJ4l.}"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"

    networks:
      proxy:
        aliases:
          #used for external stacks
          - ${COLLABORA_DOMAIN:-collabora.opencloud.test}
          - ${EURO_OFFICE_DOMAIN:-euro-office.opencloud.test}
          - ${KEYCLOAK_DOMAIN:-keycloak.opencloud.test}
          - ${OC_DOMAIN:-cloud.opencloud.test}
networks:
  proxy:
    external: true
